### ISSUE TITLE
Typo in gemspec (homepage url)

### ISSUE THREAD

**Issue by cice** [werein/prestashop#1]
Hi,
Just a quick notice: you have a typo in your gemspec, so the URL on rubygems.org pointing to the guides is wrong.
cheers!
Marian

**Comment by cice** [comment]
oh i see it's fixed already in the gemspec. nevermind ;)

**Comment by jirikolarik** [comment]
Hi Marian, thanks for using this gem and being active!:)

**Comment by cice** [comment]
Thanks for providing it! Just a quick question: I have MASSIVE connection problems with presta (cloud). In 1 out of 5 requests i experience a broken-pipe or reset-by-peer. Do you have similar problems?

**Comment by jirikolarik** [comment]
I never tried that with cloud version, but I guess that some delay between requests could help
