### ISSUE TITLE
Getting associations

### ISSUE THREAD

**Issue by josegrad** [werein/prestashop#10]
Should this be possible?

```
shop_client.connection.read :orders, nil, {:filter => { :current_state => 4 }, :display => '[associations]'}
```

It just returns an error with PS 1.6
One option is to display full but there's a lot of stuff there which I don't need.

**Comment by jirikolarik** [comment]
Theoretically. What does it says? Did you tried to display id for example? Does it work in that case?

**Comment by josegrad** [comment]
shop_client.connection.read :orders, nil, {:filter => { :current_state => 4 }, :display => '[associations]'}

Prestashop::Api::RequestFailed: Unable to display this field "associations". However, these are available: id, id_address_delivery, id_address_invoice, id_cart, id_currency, id_lang, id_customer, id_carrier, current_state, module, invoice_number, invoice_date, delivery_number, delivery_date, valid, date_add, date_upd, shipping_number, id_shop_group, id_shop, secure_key, payment, recyclable, gift, gift_message, mobile_theme, total_discounts, total_discounts_tax_incl, total_discounts_tax_excl, total_paid, total_paid_tax_incl, total_paid_tax_excl, total_paid_real, total_products, total_products_wt, total_shipping, total_shipping_tax_incl, total_shipping_tax_excl, carrier_tax_rate, total_wrapping, total_wrapping_tax_incl, total_wrapping_tax_excl, round_mode, round_type, conversion_rate, reference

Using display full brings out all the stuff, associations included. Lots of overhead however.

It seems to be a limitation of PS itself. Unfortunately.
PS likes forcing us jumping from Id to Id making several requests to get important information about orders. Fragmented API.

**Comment by jirikolarik** [comment]
Yeah, it's PS limitation, it supports only the fields you mentioned above. Api doesn't have any bulk update which is shame. Going through all items one by one is unfortunately the only way, how to communicate with PS API

**Comment by josegrad** [comment]
Thanks.
