### ISSUE TITLE
can't add manufacturer with special symbols in name

### ISSUE THREAD

**Issue by lexusnexus** [werein/prestashop#11]
For creating manufacturer with name "D & G" i use this code (with PS 1.6):
```
manufacturer = Prestashop::Mapper::Manufacturer.new(id_lang: 'id_lang', name: "D & G")
manufacturer.find_or_create
```
In result, manufacturer with name `"D &amp; G"` created.
How can I create manufacturer with name: "D & G"?

**Comment by jirikolarik** [comment]
I guess that this has to be resolved on Prestashop side, since everything has to be escaped :(
