### ISSUE TITLE
Order with multiple cart_items

### ISSUE THREAD

**Issue by plugowski** [werein/prestashop#16]
Hi,

I know that you was already surprised that someone is still using that repository but yeah, and I have new problem.

I want to create an order so I'm using Prestashop::Api::Converter.build to create proper payload but I have a problem when I want to build couple the same XML elements like under cart_items:

```
<cart_rows>
   <cart_row/>
   <cart_row/>
   <cart_row/>
   <cart_row/>
</cart_rows>
```

So I tried to pass array as items, but it doesn't work :(

```
cart_rows = []
      order.order_products.each do |product|
        cart_rows.push({
           id_product: product.product_id,
           quantity: product.qty
         })
      end

{
          id_shop: 1,
          id_customer: customer[:customer][:id],
          id_currency: currency_id,
          id_lang: language_id,
          id_address_delivery: address[:address][:id],
          id_address_invoice: address[:address][:id],
          id_carrier: carrier_id,
          secure_key: customer[:customer][:secure_key],
          associations: {
              cart_rows: cart_rows
          }
      }
```

And of course I cant create hash with the same symbols, do you have any solution for that?

**Comment by plugowski** [comment]
Damn me, I found a solution debugging XML builder 👍 

```
cart_rows = {:cart_row => []}
      order.order_products.each do |product|
        cart_rows[:cart_row].push(
            :id_product => product.product_id,
            :quantity => product.qty
         )
      end
```

So basically one index should contains an array of elements...

**Comment by jirikolarik** [comment]
That was quick :)

**Comment by plugowski** [comment]
Yeah sometimes we just need to shout something loud to find a solution :)
