### ISSUE TITLE
can't modify frozen String

### ISSUE THREAD

**Issue by tostasqb** [werein/prestashop#7]
Just started testing with Prestashop 1.6.1.4
Running `Prestashop::Client::Implementation.create 'api_key', 'api_url'` gives the error `can't modify frozen String`...

Ruby: 2.3.0
Rails: 4.2.6

**Comment by tostasqb** [comment]
The error seems to happen when the variables were set in the Environment, like

`Prestashop::Client::Implementation.create ENV['KEY'], ENV['URL']`

When setting inline, it works fine...seems odd...maybe not a bug at all

**Comment by jirikolarik** [comment]
There is wrong manipulation with api_key/api_url which is now fixed, but it's still isn't optimal
